/**
 * This file contains conversation starters for random conversations.
 * You can add, remove, or modify these starters as needed.
 */

export const conversationStarters = [
  "Tell me something funny about animals",
  "I want to do a quiz about dinosaurs",
  "Tell me something that happened today in history",
  "Can you tell me a short bedtime story?",
  "Let's play a guessing game about animals",
  "Tell me about space and planets",
  "Can you teach me a cool science fact?",
  "I want to hear a funny joke",
  "Tell me about a magical creature",
  "Can we make up a story together?",
  "Tell me something cool about the ocean",
  "I want to learn about a famous inventor",
  "Can you teach me how to say hello in different languages?",
  "Tell me about your favorite mythical creature",
  "I want to hear a riddle",
  "Let's talk about superheroes",
  "Tell me something interesting about robots",
  "Can you teach me about the weather?",
  "I want to learn about different countries",
  "Tell me about a weird animal I probably don't know",
  "Can we play 20 questions?",
  "Tell me about the biggest things in the world",
  "I want to hear about ancient Egypt",
  "Can you tell me about the rainforest?",
  "Tell me facts about my favorite animal, the dolphin",
  "I want to learn how things work",
  "Tell me about the coolest job in the world",
  "Can you explain how planes fly?",
  "I want to hear about sports records",
  "Tell me about the smallest animals in the world",
  "Can you teach me about music?",
  "I want to learn a magic trick",
  "Tell me something about the human body",
  "Can we make up a silly song?",
  "I want to hear about the fastest animals",
  "Tell me how to make something cool at home",
  "Can you tell me about different types of plants?",
  "I want to learn about space exploration",
  "Tell me a fun fact about food",
  "Can we talk about books?",
  "I want to hear about amazing buildings",
  "Tell me something surprising about insects",
  "Can you help me solve a mystery?",
  "I want to learn about the Arctic",
  "Tell me about the solar system",
  "Can you explain how computers work?",
  "I want to hear about pirates",
  "Tell me something about trains",
  "Can we invent a new superhero?",
  "I want to learn about volcanoes",
  "Tell me about the strongest animals",
  "Can you tell me why the sky is blue?",
  "I want to hear about different types of cars",
  "Tell me about the tallest mountains",
  "Can we play a word game?",
  "I want to learn about prehistoric animals",
  "Tell me facts about the moon",
  "Can you explain how rainbows form?",
  "I want to hear about underwater creatures",
  "Tell me about different types of musical instruments",
  "Can we make up a new planet?",
  "I want to learn about dinosaurs",
  "Tell me how animals communicate",
  "Can you share facts about the brain?",
  "I want to hear about castles and knights",
  "Tell me about the strangest places on Earth",
  "Can we create a new holiday?",
  "I want to learn about astronauts",
  "Tell me something about wild cats",
  "Can you teach me about the seasons?",
  "I want to hear about gemstones and crystals",
  "Tell me about the biggest bugs",
  "Can we make a time capsule together?",
  "I want to learn about how movies are made",
  "Tell me about famous explorers",
  "Can you explain how trees grow?",
  "I want to hear facts about reptiles",
  "Tell me about different types of boats",
  "Can we imagine what animals would say if they could talk?",
  "I want to learn about famous scientists",
  "Tell me something about the jungle",
  "Can you tell me how electricity works?",
  "I want to hear about the deepest parts of the ocean",
  "Tell me about different types of birds",
  "Can we plan an adventure to another planet?",
  "I want to learn about how candy is made",
  "Tell me about famous paintings",
  "Can you explain how earthquakes happen?",
  "I want to hear about ancient myths",
  "Tell me about how animals survive in the desert",
  "Can we create a new language?",
  "I want to learn about famous inventions",
  "Tell me something about how bridges are built",
  "Can you teach me about money?",
  "I want to hear about different types of sports",
  "Tell me about how airplanes were invented",
  "Can we talk about the future?",
  "I want to learn about how food grows",
  "Tell me about different types of weather",
  "Can you help me imagine what it would be like to have a superpower?"
];

/**
 * German conversation starters
 */
export const germanConversationStarters = [
  "Erzähl mir etwas Lustiges über Tiere",
  "Ich möchte ein Quiz über Dinosaurier machen",
  "Erzähl mir etwas, das heute in der Geschichte passiert ist",
  "Kannst du mir eine kurze Gute-Nacht-Geschichte erzählen?",
  "Lass uns ein Ratespiel über Tiere spielen",
  "Erzähl mir über den Weltraum und Planeten",
  "Kannst du mir eine coole wissenschaftliche Tatsache beibringen?",
  "Ich möchte einen lustigen Witz hören",
  "Erzähl mir von einem magischen Wesen",
  "Können wir zusammen eine Geschichte erfinden?",
  "Erzähl mir etwas Cooles über den Ozean",
  "Ich möchte etwas über einen berühmten Erfinder lernen",
  "Kannst du mir beibringen, wie man Hallo in verschiedenen Sprachen sagt?",
  "Erzähl mir von deinem Lieblingsmythenwesen",
  "Ich möchte ein Rätsel hören",
  "Lass uns über Superhelden sprechen",
  "Erzähl mir etwas Interessantes über Roboter",
  "Kannst du mir etwas über das Wetter beibringen?",
  "Ich möchte etwas über verschiedene Länder lernen",
  "Erzähl mir von einem seltsamen Tier, das ich wahrscheinlich nicht kenne",
  "Können wir 20 Fragen spielen?",
  "Erzähl mir von den größten Dingen der Welt",
  "Ich möchte etwas über das alte Ägypten hören",
  "Kannst du mir etwas über den Regenwald erzählen?",
  "Erzähl mir Fakten über mein Lieblingstier, den Delfin",
  "Ich möchte lernen, wie Dinge funktionieren",
  "Erzähl mir vom coolsten Job der Welt",
  "Kannst du erklären, wie Flugzeuge fliegen?",
  "Ich möchte etwas über Sportrekorde hören",
  "Erzähl mir von den kleinsten Tieren der Welt",
  "Kannst du mir etwas über Musik beibringen?",
  "Ich möchte einen Zaubertrick lernen",
  "Erzähl mir etwas über den menschlichen Körper",
  "Können wir ein albernes Lied erfinden?",
  "Ich möchte etwas über die schnellsten Tiere hören",
  "Erzähl mir, wie man etwas Cooles zu Hause macht",
  "Kannst du mir von verschiedenen Pflanzenarten erzählen?",
  "Ich möchte etwas über Weltraumforschung lernen",
  "Erzähl mir einen lustigen Fakt über Essen",
  "Können wir über Bücher sprechen?",
  "Ich möchte etwas über erstaunliche Gebäude hören",
  "Erzähl mir etwas Überraschendes über Insekten",
  "Kannst du mir helfen, ein Rätsel zu lösen?",
  "Ich möchte etwas über die Arktis lernen",
  "Erzähl mir vom Sonnensystem",
  "Kannst du erklären, wie Computer funktionieren?",
  "Ich möchte etwas über Piraten hören",
  "Erzähl mir etwas über Züge",
  "Können wir einen neuen Superhelden erfinden?",
  "Ich möchte etwas über Vulkane lernen",
  "Erzähl mir von den stärksten Tieren",
  "Kannst du mir sagen, warum der Himmel blau ist?",
  "Ich möchte etwas über verschiedene Autotypen hören",
  "Erzähl mir von den höchsten Bergen",
  "Können wir ein Wortspiel spielen?",
  "Ich möchte etwas über prähistorische Tiere lernen",
  "Erzähl mir Fakten über den Mond",
  "Kannst du erklären, wie Regenbögen entstehen?",
  "Ich möchte etwas über Unterwasserlebewesen hören",
  "Erzähl mir von verschiedenen Musikinstrumenten",
  "Können wir einen neuen Planeten erfinden?",
  "Ich möchte etwas über Dinosaurier lernen",
  "Erzähl mir, wie Tiere kommunizieren",
  "Kannst du Fakten über das Gehirn teilen?",
  "Ich möchte etwas über Burgen und Ritter hören",
  "Erzähl mir von den seltsamsten Orten der Erde",
  "Können wir einen neuen Feiertag erfinden?",
  "Ich möchte etwas über Astronauten lernen",
  "Erzähl mir etwas über Wildkatzen",
  "Kannst du mir etwas über die Jahreszeiten beibringen?",
  "Ich möchte etwas über Edelsteine und Kristalle hören",
  "Erzähl mir von den größten Insekten",
  "Können wir zusammen eine Zeitkapsel erstellen?",
  "Ich möchte lernen, wie Filme gemacht werden",
  "Erzähl mir von berühmten Entdeckern",
  "Kannst du erklären, wie Bäume wachsen?",
  "Ich möchte Fakten über Reptilien hören",
  "Erzähl mir von verschiedenen Bootstypen",
  "Können wir uns vorstellen, was Tiere sagen würden, wenn sie sprechen könnten?",
  "Ich möchte etwas über berühmte Wissenschaftler lernen",
  "Erzähl mir etwas über den Dschungel",
  "Kannst du mir sagen, wie Elektrizität funktioniert?",
  "Ich möchte etwas über die tiefsten Teile des Ozeans hören",
  "Erzähl mir von verschiedenen Vogelarten",
  "Können wir ein Abenteuer zu einem anderen Planeten planen?",
  "Ich möchte lernen, wie Süßigkeiten hergestellt werden",
  "Erzähl mir von berühmten Gemälden",
  "Kannst du erklären, wie Erdbeben entstehen?",
  "Ich möchte etwas über antike Mythen hören",
  "Erzähl mir, wie Tiere in der Wüste überleben",
  "Können wir eine neue Sprache erfinden?",
  "Ich möchte etwas über berühmte Erfindungen lernen",
  "Erzähl mir etwas darüber, wie Brücken gebaut werden",
  "Kannst du mir etwas über Geld beibringen?",
  "Ich möchte etwas über verschiedene Sportarten hören",
  "Erzähl mir, wie Flugzeuge erfunden wurden",
  "Können wir über die Zukunft sprechen?",
  "Ich möchte lernen, wie Lebensmittel wachsen",
  "Erzähl mir von verschiedenen Wetterarten",
  "Kannst du mir helfen, mir vorzustellen, wie es wäre, eine Superkraft zu haben?"
];

/**
 * Get a random conversation starter based on the language
 * @param language The language to use ('english' or 'german')
 * @returns A random conversation starter in the specified language
 */
export function getRandomConversationStarter(language: 'english' | 'german'): string {
  const starters = language === 'german' ? germanConversationStarters : conversationStarters;
  const randomIndex = Math.floor(Math.random() * starters.length);
  return starters[randomIndex];
} 